# Copyright (c) 2024 Nordic Semiconductor ASA
# SPDX-License-Identifier: Apache-2.0
#
# This file contains selected Kconfig options for the power shield sample.

CONFIG_SENSOR=y
CONFIG_BLINK=y
CONFIG_LOG=y
CONFIG_APP_LOG_LEVEL_INF=y
